### ISSUE TITLE
TIR JOUEUR

### ISSUE THREAD

**Issue by Zyre28** [Darkbriks/L2_LOO_Projet_2#19]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Darkbriks** [comment]
Certaint types de tir du joueur pourrait detruire des morceau de decor (on récupére le(s) collider(s) touché, et on les envoi dans unne function de ChunkManager pour les detruire, et detruire en même temp la Tile et le Vector4 associé
